version: '3.8'

services:
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
            - MONGO_LOG_DIR=/data/logs
            - MONGO_DATA_DIR=/data/db
        ports:
            - ${MONGO_PORT}:${MONGO_PORT}
        volumes:
            - ./storage/mongo/data:/data/db
            - ./storage/mongo/log:/data/logs

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        depends_on:
            - mongo
        environment:
            - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
            - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
        ports:
            - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}

    redis:
        image: redis:alpine
        container_name: redis
        environment:
            - REDIS_REPLICATION_MODE=master
            - REDIS_LOG_DIR=/var/lib/redis
            - REDIS_DATA_DIR=/var/lib/redis
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        volumes:
            - ./storage/redis/data:/var/lib/redis
            - ./storage/redis/log:/var/log/redis
        command: redis-server

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        depends_on:
            - redis
        environment:
            - PORT=${REDIS_COMMANDER_PORT}
            - READ_ONLY=true
            - REDIS_HOSTS=local:redis:${REDIS_PORT}
        ports:
            - ${REDIS_COMMANDER_PORT}:${REDIS_COMMANDER_PORT}

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        ports:
            - ${RABBIT_MQ_API_PORT}:${RABBIT_MQ_API_PORT}
            - ${RABBIT_MQ_UI_PORT}:${RABBIT_MQ_UI_PORT}
        volumes:
            - ./storage/rabbitmq/data/:/var/lib/rabbitmq/
            - ./storage/rabbitmq/log/:/var/log/rabbitmq/