version: '3.8'

services:
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        command: [--auth]
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_LOG_DIR=/data/logs
            - MONGO_DATA_DIR=/data/db
        ports:
            - ${MONGO_PORT}:${MONGO_PORT}
        volumes:
            - ./storage/mongo/data:/data/db
            - ./storage/mongo/log:/data/logs

    redis:
        image: redis:alpine
        container_name: redis
        environment:
            - REDIS_REPLICATION_MODE=master
            - REDIS_USER=${REDIS_USERNAME}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_LOG_DIR=/var/lib/redis
            - REDIS_DATA_DIR=/var/lib/redis
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        volumes:
            - ./storage/redis/data:/var/lib/redis
            - ./storage/redis/log:/var/log/redis
        command: redis-server --requirepass ${REDIS_PASSWORD}

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        ports:
            - ${RABBIT_MQ_API_PORT}:${RABBIT_MQ_API_PORT}
            - ${RABBIT_MQ_UI_PORT}:${RABBIT_MQ_UI_PORT}
        volumes:
            - ./storage/rabbitmq/data/:/var/lib/rabbitmq/
            - ./storage/rabbitmq/log/:/var/log/rabbitmq/