version: '3.8'

networks:
    readonly:
    writeonly:

services:
    portal-read:
        restart: unless-stopped
        build:
            context: ./apps/portal-read
            target: production
            dockerfile: Dockerfile
        depends_on:
            - redis
        expose:
            - ${READ_PORT}
        volumes:
            - ./apps/portal-read:/app
        command: npm start:dev
        networks:
            - readonly

    portal-write:
        restart: unless-stopped
        build:
            context: ./apps/portal-write
            target: production
            dockerfile: Dockerfile
        depends_on:
            - rabbitmq
        expose:
            - ${WRITE_PORT}
        volumes:
            - ./apps/portal-write:/app
        command: npm start:dev
        networks:
            - writeonly

    redis:
        image: debian:bullseye-slim
        expose:
            - ${REDIS_PORT}
        networks:
            - readonly

    rabbitmq:
        image: rabbitmq:3-management-alpine
        expose:
            - ${RABBIT_MQ_API_PORT}
            - ${RABBIT_MQ_UI_PORT}
        volumes:
            - ./storage/rabbitmq/data/:/var/lib/rabbitmq/
            - ./storage/rabbitmq/log/:/var/log/rabbitmq/
        networks:
            - writeonly
