version: '3.8'

networks:
    readonly:
    writeonly:

services:
    read:
        image: node:16
        working_dir: ./apps/portal-read
        depends_on:
            - redis
        expose:
            - ${READ_PORT}
        volumes:
            - ./apps/portal-read/pmpm-lock.yaml:pnpm-lock.yaml
        command:
            sh -c 'rushx install && rushx start'
        networks:
            - readonly

    write:
        image: node:16
        working_dir: ./apps/portal-write
        depends_on:
            - rabbitmq
        expose:
            - ${WRITE_PORT}
        volumes:
            - ./apps/portal-write/pmpm-lock.yaml:pnpm-lock.yaml
        command:
            sh -c 'rushx install && rushx start'
        networks:
            - writeonly

    redis:
        image: debian:bullseye-slim
        expose:
            - ${REDIS_PORT}
        networks:
            - readonly

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - ${RABBIT_MQ_API_PORT}:${RABBIT_MQ_API_PORT}
            - ${RABBIT_MQ_UI_PORT}:${RABBIT_MQ_UI_PORT}
        volumes:
            - ./storage/rabbitmq/data/:/var/lib/rabbitmq/
            - ./storage/rabbitmq/log/:/var/log/rabbitmq/
        networks:
            - writeonly
