version: '3.8'

services:
    redis:
        image: redis:alpine
        environment:
            - REDIS_REPLICATION_MODE=master
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        command: redis-server --requirepass ${REDIS_PASSWD}

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - ${RABBIT_MQ_API_PORT}:${RABBIT_MQ_API_PORT}
            - ${RABBIT_MQ_UI_PORT}:${RABBIT_MQ_UI_PORT}
        volumes:
            - ./storage/rabbitmq/data/:/var/lib/rabbitmq/
            - ./storage/rabbitmq/log/:/var/log/rabbitmq/