#!/bin/bash
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# Detect and init asdf
ASDF_DIR="$(brew --prefix --installed asdf 2>/dev/null || printf %s "$HOME/.asdf")"
[ -s "$ASDF_DIR/asdf.sh" ] && \. "$ASDF_DIR/asdf.sh"

# Detect and init nvm
NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Invoke the "rush format-staged" custom command to reformat files whenever they
# are committed. The command is defined in common/config/rush/command-line.json
# and uses the "rush-format" autoinstaller.
node common/scripts/install-run-rush.js format-staged || exit $?

# Invoke the "rush lint" custom command to lint projects before new changes
# will be committed. The command is defined in common/config/rush/command-line.json
# It runs the `lint` script in every project where it was defined.
node common/scripts/install-run-rush.js lint --fix || exit $?
